### ISSUE TITLE
A few feature ideas.

### ISSUE THREAD

**Issue by Ashlytical** [wendall911/BetterDays#1]
I saw that you have fabric seasons compat, but there are a few questions and features Id like to ask about.

- You mentioned being able to slow down time to be the same length as a real life day, but do you think it would be possible for a way to sync ingame time to real life in a way where even the seasons match up with it. (So the daytime, and time of year for compat with seasons.)

- Theres mods in which they allow sleeping during the day, do you know if that would be compatible with this mod? 

Much love - Ashly.

**Comment by wendall911** [comment]
This isn't the right mod, or even the right game for this type of functionality. Basically, the time system is broken in Minecraft. Even if you try and sync, there isn't enough granularity in the tick system to not create some drift. I might consider it, but given it is such a niche request, I am not sure I would want to put in the time to do so given the complexities involved.

If using Serene Seasons, you'd have to do a bunch of math to get the seasons to match. This might work, but not sure. Same goes for Fabric Seasons. They change seasons in a set number of days. This could work, but would drift as well.

Here is some more explanation in an Hourglass issue on this: https://github.com/DuckyCrayfish/hourglass/issues/52 Includes the value you'd have to use to get realtime days. The Hourglass author has been talking about doing this for years, but has not been maintaining the mod.

There are other time mods that this is possible with, but they do bad things and break lots of other mods. So this is achievable, but probably won't work very well in any given situation.

As for compatibility with other mods that allow sleeping during the day, it should work. However, if using the sleep feature, you'll need to change this:

#When true, players are allowed to sleep at all times of day in dimensions controlled by Better Days.
	#Note: Other mods may override this ability.
	allowDaySleep = false

If it isn't compatible, you'll need to disable the sleep mechanic in this mod for it to work.

**Comment by Ashlytical** [comment]
Thanks for the reply, I understand how complicated it would be and it makes sense that it wouldn't be worthwhile since it truly incredibly niche, and I hadn't noticed the daysleep feature, so thank you! - ♥
