### ISSUE TITLE
Config option suggestion: % of players for time speed-up

### ISSUE THREAD

**Issue by Cephelo** [wendall911/BetterDays#12]
A config option that determines the percentage of players on the server that need to be sleeping for time-speed up to take effect would be awesome!

For example, if a server has 15 players online, and the config option is set to 50% (0.5), then 8 or more players must be sleeping to start the time speed-up.  This is when the "sleepSpeedMin" option would be triggered.  This would let server admins prevent everyone from skipping time if only one person is sleeping, and require coordination for mutual benefit if sleeping speeds up crop growth, for example.

To emulate the current way things are, this option could be set to 0.0, which would disable this feature (or render it ineffective)

Let me know what you think, or if there's any way I can help.  Thanks!

**Comment by wendall911** [comment]
I think we never added this, as there are a bunch of sleep vote mods out there. I do think this is a reasonable request though. I'll look into this and see what I can do. Thanks for the suggestion!

**Comment by wendall911** [comment]
Actually, after a quick check, this is already possible. Just set the gamerule for playersSleepingPercentage and it will be honored.
