### ISSUE TITLE
[Modrinth] Mod description cut off at bottom?

### ISSUE THREAD

**Issue by ratemisia** [wendall911/BetterDays#15]
![image](https://github.com/user-attachments/assets/192ba94d-32c8-4b54-9741-6965cd120ece)
It appears that the description of this mod on Modrinth ends in the middle of a sentence. I understand that this is not a mod issue, but I felt that this was the best place to bring it to your attention.

**Comment by wendall911** [comment]
Thanks for reporting. It was just missing a word "installation." at the end.
