### ISSUE TITLE
[request]: add compat for "Hay Beds"

### ISSUE THREAD

**Issue by vinnyg0621** [wendall911/BetterDays#17]
here is the mod link:
https://www.curseforge.com/minecraft/mc-mods/hay-beds

**Comment by wendall911** [comment]
What would the compat consist of? Unless they are messing with the vanilla sleep, there isn't anything to be done.

**Comment by vinnyg0621** [comment]
read the description in the mod's page,I think they are kinda messing with vanilla sleep.

**Comment by wendall911** [comment]
There is a config option to disable the sleep mechanics in better days. I am going to close this as I can't support mods messing with sleep at all, hence the ability to disable it entirely and still use the day/night length feature (which is the primary purpose of the mod) the sleep feature is just an extra.
