### ISSUE TITLE
Breaks in the Aether; Dimension blacklist?

### ISSUE THREAD

**Issue by den-commits** [wendall911/BetterDays#19]
While in the Aether dimension (aether:the_aether), the sun constantly snaps back to where it would have been had BetterDays not been altering the speed, including both the standard day/night cycle and their eternal_day rule. The issue stops when BetterDays is disabled. Would it be possible to implement a dimension blacklist for BetterDays? Thank you!

NeoForge 1.21.1
aether-1.21.1-1.5.0-neoforge.jar (this is their prerelease version for 1.21.1)
betterdays-1.21.1-3.1.0.7-NEOFORGE.jar

Edit: I actually just noticed this, so maybe they're doing something funky with how they're handling time in that dimension:
> BetterDays: The Overworld is currently the only dimension supported. However, most dimensions in Minecraft (including custom dimensions) derive their time information from the Overworld and will therefore elapse time at the same rate.

**Comment by wendall911** [comment]
Ok, let me take a look and I'll see what I can figure out. I think a blacklist for dimensions is a good idea.

**Comment by wendall911** [comment]
I just built the latest and the sun is just stuck in place overhead. I don't see any issues with Better Days at all.

**Comment by wendall911** [comment]
Ok, I can reproduce if using /time set command Let me see what I can figure out.

**Comment by wendall911** [comment]
The annoying mod owo sets gamerule doDaylightCycle to false when in development mode. I'm not sure why this library is so popular :shrug: I don't think setting anything in development mod is a good idea, as it breaks testing badly. Anyhow, I am adding a setting to the client config and and added the_aether as a default. I'll release it once I can test in all versions. I'll comment here soon.

**Comment by wendall911** [comment]
Ok, published everywhere, should work now. Thanks for reporting! I think this is a good feature for this type of case. Shouldn't be common, but when it happens, it is good to have some solution in the config.

**Comment by wendall911** [comment]
The annoying mod owo sets gamerule doDaylightCycle to false when in development mode. I'm not sure why this library is so popular :shrug: I don't think setting anything in development mod is a good idea, as it breaks testing badly. Anyhow, I am adding a setting to the client config and and added the_aether as a default. I'll release it once I can test in all versions. I'll comment here soon.
