### ISSUE TITLE
Crash on server with 1.21.1-3.1.1.0, re SpectreLib?

### ISSUE THREAD

**Issue by cocoa005** [wendall911/BetterDays#20]
Hi,

After updating my server to the latest 1.21.1-3.1.1.0 version of Better Days, my server is unable to finish starting up. I receive an error pertaining to SpectreLib, which I believe is embedded in your mod.

Crash report: https://mclo.gs/RRB9GBC

Latest log: https://mclo.gs/K6dhJeQ

I would appreciate any assistance you may provide.

**Comment by wendall911** [comment]
Oh, thanks for the report. Roll back to the previous version until I can figure this out. I added a config value, and I think I know the issue!

**Comment by wendall911** [comment]
Ok, fixed and uploaded on CurseForge and Modrinth.... huge apologies, I had  a massive headache yesterday and thought I could do some release stuff. I didn't test thoroughly and was trying to load the new client config stuff on the server :( Will work as expected now!

**Comment by Silverbolt666** [comment]
Hey, found the same issue on 1.20.1, didn't want to open a new issue (sorry for the incontinence)

**Comment by wendall911** [comment]
@Silverbolt666 It is fixed and deployed a few hours ago. What version are you having the issue with? I removed all 3.1.1.0 files. Should have 3.1.1.1 now.

**Comment by Silverbolt666** [comment]
@wendall911 it was on forge, but I'm sorry, for me the platform didn't update the files. I saw your update thanks for the reply ^-^

**Comment by wendall911** [comment]
@Silverbolt666 No worries, it was a rough day for me yesterday. I shouldn't have pushed that update out. Wanted to make sure everything is fixed!

**Comment by Silverbolt666** [comment]
@wendall911 it's ok! We all have one of those, I hope everything is better with you :) Thanks for the mod it's great ^-^
