### ISSUE TITLE
Better Days not working with fabric?

### ISSUE THREAD

**Issue by einfreezer** [wendall911/BetterDays#23]
Ive tried my best but it seems it wont work on my MP server. I can edit the common.toml file how often i want. Nothing happens

**Comment by wendall911** [comment]
@einfreezer This is pretty vague. What version of MC? And what version of Better Days? Is the server stopped when you are editing? Are you stopping the server before editing configs? If not, stop the server, edit and start again.

**Comment by einfreezer** [comment]
Im so sorry. My fault the Server crashed everytime after the editing but ive forgot the API Fabric mod
