### ISSUE TITLE
Config isn't respected and resets no matter what I try to do

### ISSUE THREAD

**Issue by Sipxer** [wendall911/BetterDays#3]

**Comment by RafaInformatico** [comment]
Same here. Every time I start playing the day and night multipliers are set to 2.0, which is the first value I tried. The config file betterdays-common.toml shows 2.0 but if I edit it manually the game takes it right. It's a workaround, but I can live with that.

**Comment by wendall911** [comment]
I've seen this, and I think it is a bug in SpectreLib. I'm updating it soon on all versions. If you see this in the future, the thing to do is completely stop the game. Edit the file and start. I think it is a problem with editing while the game is running. I'll keep testing and see if I can reproduce this.

**Comment by wendall911** [comment]
This has been resolved in SpectreLib
