### ISSUE TITLE
Serene Season Fix

### ISSUE THREAD

**Issue by StarlightSovereign** [wendall911/BetterDays#8]
I have set Better days with the intention to have the day last longer than the night. I have the day setting at .1 and the night setting at 2 (after experimenting and finding that it wants me to reverse the math from what I expected). This results in 28800 day duration. 

However the Serene Seasons Fix reasds:

	#A reimplementation of 'Serene Seasons Fix' that overrides the fact that Serene Seasons doesn't honor the minecraft clock.
	#If using this, Serene Seasons config value day_duration is set to 24000
	#Set to true to override.
	sereneSeasonsFix = true

Which suggests that it will reset that Serene seasons config to 24000 if enabled. 

I have noticed that the seasons seem to be going by faster than intended. 

Does this mean that I need that value set to false or true? 

The reason I write this as an issue is I think the comments as written are very confusing and might need to change. 
Saying Set True to Overridde after explaining that SS config value is changed by this setting, that would seem to imply that you're setting serene seasons fix to on or that you're setting it to override the setting of the value to 24000. It isn't clear which thing you're enabling. I assume you're enabling the Fix itself? If so, that second comment confuses the matter with the way it's worded.

Regardless, I don't know which setting I want because I don't know what is going to happen if I set it to true. 
I need the duration to be set to the same as in Better Days. If the Serene Seasons fix also sets the duration wrong in Serene Seasons that kinda defeats the purpose. How do I get these two mods aligned?

**Comment by wendall911** [comment]
SereneSeasons fix needs to be installed separately now. Removed this feature.
