### ISSUE TITLE
Increase day range to encompass the whole sunset and sunrise

### ISSUE THREAD

**Issue by amlib** [wendall911/BetterDays#9]
Here is my use case for your mod: I like being able to stretch daylight in order to also increase the amount of time it takes for a full sunset and sunrise to occur, while keeping nights short. This has a tendency to look more natural with the sun moving at a more pleasing slower pace plus allowing the user to savor such moments when using shaders that have nice graphics during those hours. However, I've noticed that after a point in the sunset/sunrise sequence, things speed up presumably because the mod is already considering that night has started or that night has not ended yet.

Indeed, looking at the code I found that Common/src/main/java/betterdays/time/TimeService.java contains the following constants:

    /** Time of day when the sun rises above the horizon. */
    public static final Time DAY_START = new Time(23500);

    /** Time of day when the sun sets below the horizon. */
    public static final Time NIGHT_START = new Time(12500);

According to https://minecraft.fandom.com/wiki/Daylight_cycle sunset ends at 13000 and sunrise starts at 23000, which also corresponds to what visually happens with shaders, you can see faint light all the way to 13000 and faint light starts appearing at 2300.

I would like to purpose the above constants to be changed to 23000 and 13000 or even better let the user tweak then at runtime.

I used to use the mod https://modrinth.com/mod/opticmanager which seemed to behave like what I'm proposing.

**Comment by wendall911** [comment]
I used to have everything segmented like this, but removed the feature. I agree that this is a much better way, but haven't figured out how I would implement so people don't get confused. (Yes, lots get confused about how the config works.) I will take a look at opticmanager and see what I can come up with.

BTW, what version of Minecraft are you looking for support in?

**Comment by amlib** [comment]
I'm using 1.20.1, and I think it's the most popular target for fabric mods right now. 

Thanks for looking into it!

**Comment by wendall911** [comment]
I added this as a configuration to all versions. Available on CurseForge and Modrinth. Thanks for the suggestion.

**Comment by amlib** [comment]
Thanks, it works perfectly!

**Comment by wendall911** [comment]
Awesome. Thanks again for the suggestion.
